# Plugins
gems: 
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "PLU Spotter Day 2015"
email: "spotterclubemg@gmail.com"
description: "O #PLUSpotterDay 2015 é um evento que reunirá os amantes da aviação no tradicional Aeroporto da Pampulha (SBBH), em Belo Horizonte."
baseurl: "/pluspotterday"
url: "https://spotterclube.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-70369466-1"
googleAnalyticsSiteUrl: "spotterclube.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Spotter Clube MG"
organizerAlternateName: "Spotter Clube MG"
organizerDescription: "O Spotter Clube MG é uma associação que visa a união entre os spotters."
organizerEmail: "ecabrera@infraero.gov.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://fb.com/spotterclubemg"

# Head
metaKeywords: "evento, plu, spotter, spotterday, spotting, pampulha, belo horizonte, sbbh, minas gerais"
twitterAccount: "@spotterclubemg"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/programacao/", text: "Programação"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Inscreva-se"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "#PLUSpotterDay <typeout> 2015"
eventDate: "5 de dezembro de 2015"
heroButtons:
 - {permalink: "/#tickets", text: "Inscreva-se"}

# About Block
aboutTitle: "Sobre o #PLUSpotterDay 2015"
aboutBlock:
 - {title: "Plane Spotting", image: "torre-plu.jpg", text: "Acesso a áreas exclusivas de SBBH aos spotters, proporcionando um olhar diferenciado do aeroporto!" }
 - {title: "Networking", image: "workshop.jpg", text: "Um dia inteiro dedicado à observação e fotografia de aeronaves, com intensa troca de experiências entre os spotters!" }
 - {title: "Integração", image: "cabine-ejet-az.jpg", text: "Frente a frente com a tradicional comunidade aeronáutica de Belo Horizonte." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {specialCharacter: "+", count: "100", info: "spotters", detail: "no #CNFSpotterDay 2015"}
 - {count: "9", specialCharacter: "+", info: "horas", detail: "de evento"}
 - {count: "2", specialCharacter: "", info: "spotting points", detail: "para registrar os melhores ângulos"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "JUMP Brasil"
eventStreetAddress: "R. Cap. Lima, 420 - Santo Amaro"
eventAddressLocality: "Recife"
eventAddressLocalityRegion: "Pernambuco"
eventPostalCode: "50040-080"
eventAddressCountry: "Brasil"
eventStartTime: "2015-11-25T19:00 -0300"
eventDoorTime: "19:00"
eventEndTime: "2015-11-25T21:00 -0300"
eventPlaceCoordinates: "-8.052448, -34.880160"
mapCenterCoordinates: "-8.052448, -34.880160"
mapMobileCenterCoordinates: "-8.052448, -34.880160"

# Venue Block
venueBlockTitle: "Complexo Aeroportuário"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Aeroporto da Pampulha<br />(IATA: PLU / ICAO: SBBH)"
venueFeatures: ["Dimensões da Pista (13/31): 2.364 m x 45 m", "Capacidade/ano: 2,2 milhões de passageiros", "Distante 8,3 km do Centro de Belo Horizonte"]

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um Patrocinador!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Registre-se para participar do #PLUSpotterDay 2015"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registros serão limitados. Somente os spotters devidamente registrados e confirmados terão acesso ao evento."

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://facebook.com/spotterclubemg", icon: "facebook"}
 - {link: "https://www.youtube.com/channel/UCWQ8Ohw9s7GsTiOS81x-dbA", icon: "youtube"}
  - {link: "https://www.flickr.com/photos/131749357@N07/", icon: "flickr"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/spotterclubemg/", text: "fb.com/SpotterClubeMG"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:spotterclubemg@gmail.com", text: "spotterclubemg@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/codigo-de-conduta/", text: "Código de Conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "pluspotterday2015"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "O Spotter Clube MG é formado por aficcionados pela aviação, como você! Faça parte dessa família também, inscreva-se já e se torne um associado."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Spotting Points"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Conheça os Spotting Points"
hackathonRows:
 - {title: "Spotting Point #1 Posto 6 (Pátio Norte)", image: "hackathon-0.png", details: "Texto sobre o Spotting Point #1 Posto 6 (Pátio Norte)!"}
 - {title: "Spotting Point #2  (Pátio Sul)", image: "hackathon-1.png", details: "Texto sobre o Spotting Point #1 Posto 6 (Pátio Norte)."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
