# Plugins
gems: 
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "PLU Spotter Day 2015"
email: "spotterclubemg@gmail.com"
description: "O #PLUSpotterDay 2015 é um evento que reunirá os amantes da aviação no tradicional Aeroporto da Pampulha (SBBH), em Belo Horizonte."
baseurl: "/pluspotterday"
url: "https://spotterclube.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-70369466-1"
googleAnalyticsSiteUrl: "spotterclube.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Spotter Clube MG"
organizerAlternateName: "Spotter Clube MG"
organizerDescription: "O Spotter Clube MG é uma associação que visa a união entre os spotters."
organizerEmail: "spotterclubemg@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://spotterclube.github.io"

# Head
metaKeywords: "evento, plu, spotter, spotterday, spotting, pampulha, belo horizonte, sbbh, minas gerais"
twitterAccount: "@spotterclubemg"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programação"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Inscreva-se"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "#PLUSpotterDay <typeout> 2015"
eventDate: "5 de dezembro de 2015"
heroButtons:
 - {permalink: "/#tickets", text: "Inscreva-se"}

# About Block
aboutTitle: "Sobre o #PLUSpotterDay 2015"
aboutBlock:
 - {title: "Plane Spotting", image: "torre-plu.jpg", text: "Acesso a áreas exclusivas de SBBH aos spotters, proporcionando um olhar diferenciado do aeroporto!" }
 - {title: "Networking", image: "workshop.jpg", text: "Um dia inteiro dedicado à observação e fotografia de aeronaves, com intensa troca de experiências entre os spotters!" }
 - {title: "Integração", image: "cabine-ejet-az.jpg", text: "frente a frente com a tradicional comunidade aeronáutica de Belo Horizonte." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {specialCharacter: "+", count: "100", info: "spotters", detail: "no #CNFSpotterDay 2015"}
 - {count: "9", specialCharacter: "+", info: "horas", detail: "de evento"}
 - {count: "2", specialCharacter: "", info: "spotting points", detail: "para registrar os melhores ângulos"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Aeroporto de Belo Horizonte/Pampulha - Carlos Drummond de Andrade"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Complexo Aeroportuário"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Aeroporto da Pampulha<br />(IATA: PLU / ICAO: SBBH)"
venueFeatures: ["Dimensões da Pista (13/31): 2.364 m x 45 m", "Capacidade/ano: 2,2 milhões de passageiros", "Distante 8,3 km do Centro de Belo Horizonte"]

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um Patrocinador!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Registre-se para participar do #PLUSpotterDay 2015"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registros serão limitados. Somente os spotters devidamente registrados e confirmados terão acesso ao evento."


# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://instagram.com/spotterclubemg", icon: "instagram"}
 - {link: "https://facebook.com/spotterclubemg", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/spotterclubemg/", text: "fb.com/SpotterClubeMG"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:spotterclubemg@gmail.com", text: "spotterclubemg@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/codigo/", text: "Código de Conduta"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "pluspotterday2015"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "O Spotter Clube MG é formado por aficcionados pela aviação, como você! Faça parte dessa família também, inscreva-se já e se torne um associado."


# Logistics Find Way Block
findWayTitle: "Descubra seu caminho aqui"
findWayDistance: "Distância"
findWayDriving: "DIRIGINDO"
findWayWalking: "CAMINHANDO"
findWayBicycling: "PEDALANDO"
findWayTransit: "TRÂNSITO"
findWayFindFlight: "Encontre o Voo"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Conheça Belo Horizonte"
directionDetailsCards:
 - {title: "Do Aeroporto", information: 'O Aeroporto Internacional Tancredo Neves / Confins (CNF/SBCF) é a principal porta de entrada da capital mineira, sendo origem e destino de boa parte dos voos comerciais. É acessível por ônibus, taxi ou veículos particulares.'}
 - {title: "Transporte Público", information: 'Google Transit está disponível em Belo Horizonte. Encontre suas rotas facilmente com o Google Maps.'}
 - {title: "Hotéis", information: 'Beagás possui várias opções de hospedagem com preços acessíveis e boa localização.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Localização"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "31270-705"
hackathonAddressCountry: "Brasil"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "07:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "Ver no Google Maps"
hackathonPlaceCoordinates: "-19.8498475, -43.9548899"
hackathonMapCenterCoordinates: "-19.8498475, -43.9548899"
hackathonMapMobileCenterCoordinates: "-19.8498475, -43.9548899"
